### ISSUE TITLE
Error when trying to convert xml which contains unicode-characters

### ISSUE THREAD

**Issue by zergar** [inorton/junit2html#13]
Hi everyone,
I'm using this program for a project and was encountering a bug wherein the program would error when trying to convert a JUnitXML which contains the Euro-sign as well as an Ü / ü.

Stacktrace is 

```
Traceback (most recent call last):
  File "/usr/local/bin/junit2html", line 4, in <module>
    runner.start()
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/runner.py", line 40, in start
    run(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/runner.py", line 30, in run
    html = report.html()
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/parser.py", line 517, in html
    page += suite.html()
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/parser.py", line 327, in html
    classes.append(self.classes[classname].html())
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/parser.py", line 43, in html
    cases = [x.html() for x in self.cases]
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/parser.py", line 129, in html
    fail=tag.text(self.failure))
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/tag.py", line 14, in text
    return cgi.escape(str(content))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 67: ordinal not in range(128)

```
The Snippet of the XML:
```
<testcase name="Aufgabe 4:  Beispiel aus dem Aufgabenblatt" time="0.001" classname="Aufgabe 4: ">
    <failure type="">Expected &lt;anonymous&gt;({ 3: 1, Hi: 1, hi: 1, constructor: 1, _: 1, 10€: 2 }) to equal &lt;anonymous&gt;({ 3: 1, hi: 2, constructor: 1, _: 1, 10€: 2 }).
/home/gereon/Schreibtisch/evalTest/ex-7_9-moodle-karma-test-execution/test-classes/test_ex4.js:40:50
</failure>
  </testcase>
```

I'm using the latest version (downloaded it earlier this year).

Thanks for looking over it,
Gereon

**Comment by leilaminiailo** [comment]
I have the same issue. Please fix

**Comment by inorton** [comment]
Thanks for the report, I'll take a look
