### ISSUE TITLE
KeyError: 'name'

### ISSUE THREAD

**Issue by yodaqua** [inorton/junit2html#34]
Hi there

Thanks a million for writing this code. It has immense benefits.

I've been getting a key error.

Initial setup:

1. Run python tests using xmlrunner to produce Junit output
2. Merge JUnit XML outputs (see 2. JUnit report)
3. Run junit2html, which results in the stacktrace below.

I don't see any obvious structural differences between the Junit reports in your test folder when compared to 2. JUnit report.

Please assist.

Thanks

Don

**1. Stacktrace:**

[anaconda-ds-tools-test] Running shell script
+ junit2html junit_results.xml junit_results.html
Traceback (most recent call last):
  File "/opt/conda/bin/junit2html", line 4, in <module>
    runner.start()
  File "/opt/conda/lib/python3.6/site-packages/junit2htmlreport/runner.py", line 40, in start
    run(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/junit2htmlreport/runner.py", line 29, in run
    report = parser.Junit(args[0])
  File "/opt/conda/lib/python3.6/site-packages/junit2htmlreport/parser.py", line 419, in __init__
    self.process()
  File "/opt/conda/lib/python3.6/site-packages/junit2htmlreport/parser.py", line 464, in process
    cursuite.name = suite.attrib["name"]
KeyError: 'name'

**2. JUnit report:**

<testsuite errors="0" failures="0" tests="4" time="5.831"><testcase classname="dstools.test.test_dslogger.DsLogger" name="test_msg_logger" time="0.001" />
        <testcase classname="dstools.test.test_dslogger.DsLogger" name="test_simple_logger" time="0.000" />
        <system-out>
        </system-out>
        <system-err>
2017-12-16 09:32:59,302.302 [test] INFO test_dslogger - test_msg_logger: this is a test message
        </system-err>
<testcase classname="dstools.test.test_pyspark_project.PySparkProject" name="test_config_create" time="5.209" />
        <testcase classname="dstools.test.test_pyspark_project.PySparkProject" name="test_default_create" time="0.621" />
        <system-out>
        </system-out>
        <system-err>
2017-12-16 09:32:59,303.303 [test_config_create-2-a] INFO project - __init__: Attaching Spark Session
2017-12-16 09:33:04,359.359 [test_config_create-2-a] INFO project - __init__: Attaching model store
2017-12-16 09:33:04,359.359 [test_config_create-2-a] INFO project - __init__: application root is /tmp/workspace/bdp-demo/dev/data-science-tools/anaconda-ds-tools-test
2017-12-16 09:33:04,512.512 [test_default_create-1-arbitrary] INFO project - __init__: Attaching Spark Session
2017-12-16 09:33:04,670.670 [test_default_create-1-arbitrary] INFO project - __init__: Attaching model store
2017-12-16 09:33:04,671.671 [test_default_create-1-arbitrary] INFO project - __init__: application root is /tmp/workspace/bdp-demo/dev/data-science-tools/anaconda-ds-tools-test
        </system-err>
</testsuite>

**Comment by yodaqua** [comment]
`<testsuite errors="0" failures="0" tests="4" time="5.831"><testcase classname="dstools.test.test_dslogger.DsLogger" name="test_msg_logger" time="0.001" />
        <testcase classname="dstools.test.test_dslogger.DsLogger" name="test_simple_logger" time="0.000" />
        <system-out>
        </system-out>
        <system-err>
2017-12-16 09:32:59,302.302 [test] INFO test_dslogger - test_msg_logger: this is a test message
        </system-err>
<testcase classname="dstools.test.test_pyspark_project.PySparkProject" name="test_config_create" time="5.209" />
        <testcase classname="dstools.test.test_pyspark_project.PySparkProject" name="test_default_create" time="0.621" />
        <system-out>
        </system-out>
        <system-err>
2017-12-16 09:32:59,303.303 [test_config_create-2-a] INFO project - __init__: Attaching Spark Session
2017-12-16 09:33:04,359.359 [test_config_create-2-a] INFO project - __init__: Attaching model store
2017-12-16 09:33:04,359.359 [test_config_create-2-a] INFO project - __init__: application root is /tmp/workspace/bdp-demo/dev/data-science-tools/anaconda-ds-tools-test
2017-12-16 09:33:04,512.512 [test_default_create-1-arbitrary] INFO project - __init__: Attaching Spark Session
2017-12-16 09:33:04,670.670 [test_default_create-1-arbitrary] INFO project - __init__: Attaching model store
2017-12-16 09:33:04,671.671 [test_default_create-1-arbitrary] INFO project - __init__: application root is /tmp/workspace/bdp-demo/dev/data-science-tools/anaconda-ds-tools-test
        </system-err>
</testsuite>
`

**Comment by inorton** [comment]
Hi, the JUnit spec I've been working to requires a testsuite tag to have a `name` attribute.  Most things that generate the xml files set this that I know of.  What do you use to emit the results files?

**Comment by yodaqua** [comment]
Hi, you're right.

I've been using a merge utility [merge_junit_results.py ](https://gist.github.com/cgoldberg/4320815). I looked at the code and it drops the testsuite name attribute.

I've added it and retested. Your tool works as expected.

Thanks for the tool and thanks for your response.

**Comment by inorton** [comment]
Thanks, I've been looking for a tool to merge reports
